// <auto-generated />
namespace Mastermind_WPF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TimeChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TimeChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201807250747577_TimeChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
